added the language strings and documentation for the new run-from-lin…
numere-org/Translation pull request #10
Opened 2023-07-08 18:16 UTC by raphael-sys

### SUMMARY
Implements necessary language changes.
Resolves numere-org/NumeRe#39

*Reviewers:* @numere-org/maintainers

### DOCUMENTATION
* **Documentation articles:**
    * [x] corresponding documentation articles updated
    * [ ] new documentation articles created
    * [ ] not needed
* **Language files:**
    * [x] corresponding language files updated
    * [ ] not needed

2023-07-09 08:25 UTC, numeredev requested changes
You might also want to add `fromline` to the option keywords (in syntaxelements.nlng) as well as to add the language string for this option itself (in numere.nlng)

2023-07-09 08:25 UTC, numeredev commented on de-DE/docs/script.nhlp
> +		<keyword>from line</keyword>
Whitespaces do not work here. Use the new option to enable searching for the entry

2023-07-09 08:25 UTC, numeredev commented on en-GB/docs/script.nhlp
> +		<keyword>from line</keyword>
Same here

2023-09-11 18:32 UTC, raphael-sys commented
> You might also want to add `fromline` to the option keywords (in syntaxelements.nlng) as well as to add the language string for this option itself (in numere.nlng)

What would the return type be for this line?
'GUI_EDITOR_CALLTIP_OPT_FROMLINE=fromline=??? [%%GUI_EDITOR_CALLTIP_COMMON_OPTIONFOR%% start]'

2023-09-11 19:56 UTC, numeredev approved these changes
Changes accepted

2023-09-11 19:59 UTC, merged