Updated the documentation with the table step width option
numere-org/Translation pull request #5
Opened 2023-04-30 09:22 UTC by raphael-sys

Possibility to use a range with a specified step width as requested in ticket numere-org/NumeRe#34

Please review if keywords need to be updated in other documents too or if this is enough already.

### SUMMARY
Implements necessary language changes.
Resolves numere-org/NumeRe#34

*Reviewers:* @numere-org/maintainers

### DOCUMENTATION
* **Documentation articles:**
    * [x] corresponding documentation articles updated
    * [ ] new documentation articles created
    * [ ] not needed
* **Language files:**
    * [ ] corresponding language files updated
    * [x] not needed

2023-04-30 10:40 UTC, numeredev requested changes
Please change the mentioned items. You might as well add similar information to the `cluster.nhlp` files as those also benefit of `CLST{{i:s:e}}` syntax (which, btw., also supports things like `{a, b, c, D:E, f, G:H:I}`)

2023-04-30 10:40 UTC, numeredev commented on de-DE/docs/cache.nhlp
> +			{VAL} = TABLE(START:STEP:END,:)
```suggestion
			{VAL} = TABLE({START:STEP:END},:)

```
Needs the additional brace

2023-04-30 10:40 UTC, numeredev commented on de-DE/docs/cache.nhlp
> +		Zus�tzlich kann mittels <code>ERSTER INDEX:SCHRITTWEITE:LETZTER INDEX</code> die Schrittweite der Indizes vorgegeben werden.
```suggestion
		Zus�tzlich kann mittels <a href="nhlp://operator?frame=new"><code>{ERSTER INDEX:SCHRITTWEITE:LETZTER INDEX}</code></a> die Schrittweite der Indizes vorgegeben werden.

```

2023-04-30 10:40 UTC, numeredev commented on en-GB/docs/cache.nhlp
> +			{VAL} = TABLE(START:STEP:END,:)
```suggestion
			{VAL} = TABLE({START:STEP:END},:)

```

2023-04-30 10:40 UTC, numeredev commented on en-GB/docs/cache.nhlp
> +		Additionally, the step size of the indices can be specified using <code>FIRST INDEX:STEP WIDTH:LAST INDEX</code>.
```suggestion
		Additionally, the step size of the indices can be specified using <a href="nhlp://operator?frame=new"><code>{FIRST INDEX:STEP WIDTH:LAST INDEX}</code></a>.

```

2023-04-30 10:40 UTC, numeredev commented on en-GB/docs/find.ndb
> +TABLE(i,j)~Table object with read/write access to the element "i,j"~zwischenspeicher save cache() table() sortieren swap rename range step widht~help table()
```suggestion
TABLE(i,j)~Table object with read/write access to the element "i,j"~zwischenspeicher save cache() table() sortieren swap rename range step width~help table()

```

2023-05-02 21:21 UTC, raphael-sys commented
added the requested `clst` references as syntax examples in the help article and a keyword in the find database.

2023-05-02 21:29 UTC, raphael-sys commented
It seems like the format of the file again is broken. I will look into why this keeps happening.

2023-05-02 21:47 UTC, raphael-sys commented
Also added a missing find entry for the cluster article

2023-05-03 07:09 UTC, numeredev approved these changes
Changes approved. Can be merged.

2023-05-04 08:14 UTC, merged